export const FORM_FIELDS = {
	firstName: 'firstName',
	lastName: 'lastName',
	email: 'email',
	name: 'name',
	phone: 'phone',
	phoneNumber: 'phoneNumber',
	phonePrefix: 'phonePrefix',
	username: 'username',
	website: 'website',
	address: 'address',
	city: 'city',
	zipcode: 'zipcode',
	street: 'street',
	suite: 'suite',
	company: 'company',
	companyName: 'companyName',
	companyBs: 'companyBs',
	companyCatchPhrase: 'companyCatchPhrase',
} as const;

export const VALIDATOR_ERROR_CODE = {
	isExist: 'isExist',
} as const;

export const COUNTRY_PHONE_PREFIXES = {
	None: '-',
	United_States: '+1',
	Russia: '+7',
	Belarus: '+375',
	Egypt: '+20',
	Greece: '+30',
	Netherlands: '+31',
	Belgium: '+32',
	France: '+33',
	Spain: '+34',
	Hungary: '+36',
	Italy: '+39',
	Romania: '+40',
	Switzerland: '+41',
	United_Kingdom: '+44',
	Denmark: '+45',
	Sweden: '+46',
	Norway: '+47',
	Poland: '+48',
	Germany: '+49',
	Peru: '+51',
	Mexico: '+52',
	Cuba: '+53',
	Argentina: '+54',
	Brazil: '+55',
	Chile: '+56',
	Colombia: '+57',
	Venezuela: '+58',
	Malaysia: '+60',
	Australia: '+61',
	Indonesia: '+62',
	Philippines: '+63',
	New_Zealand: '+64',
	Singapore: '+65',
	Thailand: '+66',
	Japan: '+81',
	South_Korea: '+82',
	Vietnam: '+84',
	China: '+86',
	Turkey: '+90',
	India: '+91',
	Pakistan: '+92',
	Afghanistan: '+93',
	Sri_Lanka: '+94',
	Myanmar: '+95',
	Qatar: '+96',
	Iran: '+98',
} as const;
